name: "Pupilfirst Grading"
description: "Grade a submission in Pupilfirst LMS"
inputs:
  pass_feedback:
    description: Student feedback on pass
  fail_feedback:
    description: Student feedback on fail
  submission_data:
    description: Fields related to submission in JSON format
  passed:
    description: Status of tests on the submission
outputs:
  response: # output will be available to future steps
    description: "Response from the LMS"
runs:
  using: "node14"
  main: "dist/index.js"
