name: "Pupilfirst Grading"
description: "Grade a submission in Pupilfirst LMS"
inputs:
  pass_grade: # id of input
    description: "Grade to pass"
    required: true
    default: "2"
  fail_grade: # id of input
    description: "Grade to fail"
    required: true
    default: "1"
outputs:
  response: # output will be available to future steps
    description: "Response from the LMS"
runs:
  using: "node12"
  main: "dist/index.js"
